"""The group GL(3,2) acting on the points and lines of the Fano plane.

A Sunada pair of drums is built from three involutions a, b, c of GL(3,2).
Drum A has one tile per point of the Fano plane, drum B one tile per line.
Tile p of A is glued across its edge k to tile g_k(p); if g_k fixes p, that
edge is boundary.  B is the same with g acting on lines (by inverse transpose).
"""
import itertools

import numpy as np

VECS = [np.array(v, dtype=np.uint8) for v in itertools.product((0, 1), repeat=3) if any(v)]
KEY = {tuple(v): i for i, v in enumerate(VECS)}       # 7 nonzero vectors of F2^3


def mats():
    """All 168 invertible 3x3 matrices over F2, as uint8 arrays."""
    out = []
    for bits in itertools.product((0, 1), repeat=9):
        m = np.array(bits, dtype=np.uint8).reshape(3, 3)
        if round(np.linalg.det(m.astype(float))) % 2:
            out.append(m)
    return out


def act(m, v):
    return tuple((m.astype(int) @ v) % 2)


def perm_points(m):
    """Permutation of the 7 points induced by m."""
    return tuple(KEY[act(m, v)] for v in VECS)


def perm_lines(m):
    """Permutation of the 7 lines induced by m.  A line is a nonzero dual vector w,
    the set {v : w.v = 0}.  m sends it to m^{-T} w, which keeps incidence."""
    minv_t = np.round(np.linalg.inv(m.astype(float))).astype(int) % 2
    minv_t = minv_t.T
    return tuple(KEY[act(minv_t.astype(np.uint8), w)] for w in VECS)


def incidence():
    """N[line, point] = 1 if the point lies on the line."""
    return np.array([[int((w.astype(int) @ v) % 2 == 0) for v in VECS] for w in VECS])


GROUP = mats()
assert len(GROUP) == 168
IDENT = np.eye(3, dtype=np.uint8)
INVOLUTIONS = [m for m in GROUP if not np.array_equal(m, IDENT)
               and np.array_equal((m.astype(int) @ m) % 2, IDENT)]


def generated_order(gens):
    """Order of the permutation group on points generated by gens."""
    perms = [perm_points(g) for g in gens]
    ident = tuple(range(7))
    seen, frontier = {ident}, [ident]
    while frontier:
        nxt = []
        for p in frontier:
            for g in perms:
                q = tuple(g[i] for i in p)
                if q not in seen:
                    seen.add(q)
                    nxt.append(q)
        frontier = nxt
    return len(seen)


def gluing(perms):
    """Edge-coloured graph of a drum: for each colour k, the list of glued pairs,
    and for each tile the colours of its boundary edges."""
    pairs = {k: sorted({tuple(sorted((i, p[i]))) for i in range(7) if p[i] != i})
             for k, p in enumerate(perms)}
    return pairs


def canon(perms):
    """Canonical form of a 3-coloured gluing graph on 7 tiles, up to relabelling tiles."""
    best = None
    for sigma in itertools.permutations(range(7)):
        inv = [0] * 7
        for i, s in enumerate(sigma):
            inv[s] = i
        rel = tuple(tuple(sigma[p[inv[j]]] for j in range(7)) for p in perms)
        if best is None or rel < best:
            best = rel
    return best



def classes():
    """The distinct Sunada pairs from GL(3,2), up to relabelling tiles, swapping A and B,
    and permuting colours.  Returns a list of (A_perms, B_perms) representatives,
    each a tuple of three permutations of range(7), plus some counts."""
    triples = [t for t in itertools.product(INVOLUTIONS, repeat=3) if generated_order(t) == 168]

    def key(t):
        return tuple(m.tobytes() for m in t)
    seen, reps = set(), []
    for t in triples:
        if key(t) in seen:
            continue
        reps.append(t)
        for h in GROUP:
            hinv = np.round(np.linalg.inv(h.astype(float))).astype(int) % 2
            seen.add(key(tuple(((h.astype(int) @ m @ hinv) % 2).astype(np.uint8) for m in t)))

    def recolour(P, c):
        return tuple(P[i] for i in c)
    out = {}
    for t in reps:
        A = canon([perm_points(g) for g in t])
        B = canon([perm_lines(g) for g in t])
        best = None
        for c in itertools.permutations(range(3)):
            for a, b in ((A, B), (B, A)):
                cand = (canon(recolour(a, c)), canon(recolour(b, c)))
                if best is None or cand < best:
                    best = cand
        out.setdefault(best, t)
    return [(k[0], k[1], t) for k, t in out.items()], len(triples), len(reps)


if __name__ == "__main__":
    print(f"|GL(3,2)| = {len(GROUP)}, involutions = {len(INVOLUTIONS)}")
    N = incidence()
    print("incidence: each line has", set(N.sum(1)), "points; each point on", set(N.sum(0)), "lines")
    cls, ntrip, norb = classes()
    print(f"ordered triples of involutions generating GL(3,2): {ntrip}")
    print(f"conjugacy orbits of generating triples: {norb}")
    print(f"distinct pairs up to relabelling, swapping drums and recolouring: {len(cls)}")
    for i, (A, B, t) in enumerate(cls):
        print(f"class {i}:\n  A {A}\n  B {B}")
